### ISSUE TITLE
Feature Request for RunScript:: add possibility to retrieve a value

### ISSUE THREAD

**Issue by WWeide** [consag/fitnessefixtures#10]
### Description:
It would be very handy if it is possible to retrieve also a requested value on top of the result-code of the script. Everything is expected to be case-sensitive.

The following additional items will be needed:
- a method for setting the name of the property_file.
- a method for checking the requested value for a selected [parameter] and informing the user.

_Proposed defaults:_
- Script location:                            /appl/testautomation/testscripts/[domain]
- Log file location:                          /appl/testautomation/testscripts/[domain]/log
- Property file location:                  /appl/testautomation/testscripts/[domain]/log
- Property file-name extention:     property

[domain] : specific area if there are a lot of different groups using the same Fitnesse setup (e.g. PowerCenter) ==> /appl/testautomation/testscripts/PowerCenter/log

[parameter] : The parameter that will be written into the property_file as a 'key value pair'
==> parameter=value ( e.g. count=20)

### Attachments:
[FitnesseExampleRunScript.txt](https://github.com/consag/fitnessefixtures/files/684903/FitnesseExampleRunScript.txt)

example: name.property ([name.property.txt](https://github.com/consag/fitnessefixtures/files/684916/name.property.txt) )

### Source: https://github.com/consag/fitnessefixtures/blob/master/Fixtures/src/nl/consag/testautomation/scripts/RunScript.java

**Comment by jacbeekers** [comment]
Thanks Willem. I've created an example page for the current version and will add an example for your requested enhancement once there is something to show.
[https://fitnesse.solutions/ConsagDemo.RunScriptExample](https://fitnesse.solutions/ConsagDemo.RunScriptExample)

**Comment by jacbeekers** [comment]
Fixture released.
