### ISSUE TITLE
Code compilation throws errors

### ISSUE THREAD

**Issue by keetron** [consag/fitnessefixtures#16]
There is no project file in the code download, so finding the correct jars to match all the imports is a pain.
Do you have a list of what is in your dependencies folder so I can compile the code and check if my minor modifications make sense?

Maybe an idea to move to maven or some other build tool so compilation is not machine dependant?

**Comment by keetron** [comment]
right now I seem to have issues with:
`com.informatica.wsh.*` that gives me compiler errors

This jar is not open source, nor is it easy to find online:
```
com.siebel.data.SiebelBusComp;
com.siebel.data.SiebelBusObject;
com.siebel.data.SiebelDataBean;
com.siebel.data.SiebelException;
```

`StartWorkflow.java` is giving me compilation errors

`PdfFile.java` is giving me compiler errors

I cannot find a jar for ml.options.Options

Everything considered, if it uses closed source jars and will not compile unless on your machine, is this the right fixture for us?

**Comment by keetron** [comment]
By the way, it could be caused by versions I am using and versions you are using. What versions of your dependencies do you have in place?

**Comment by jacbeekers** [comment]
To answer you questions:
Next week I will have a discussion with the team on using Gradle. Maybe we will use a different approach, but I will let you know the outcome.
With regards to the compilation errors and availability of some of the jars: Indeed, some jars, like the Siebel jars and Informatica jars are not open source and will only be available if you have gotten them from the project team that licensed the Oracle Siebel and Informatica software.
If you don't need fixtures that run against Oracle Siebel or Informatica software, you could, as a work-around, remove them from the downloaded source.

I will come back on your questions regarding depending jars and their versions.

**Comment by keetron** [comment]
Wait, so the jar you are distributing contains closed source / proprietary dependencies that are compiled into it?
As an aside, anyone using this already has licences to the Oracle or Informatica applications, just that from an open source perspective it seems... odd.

**Comment by keetron** [comment]
Siebel I removed from the project, Informatica jar I need. I will contact the sys admin at my org to provide the jar.
Would you have a name and version for this jar?

Another I cannot locate is: import ml.options.Options;
It seems there is nowhere on the internet that recognises this. Can you give me a jar name and version?

**Comment by keetron** [comment]
Wanted to ask you to have a look at:
https://github.com/keetron/fitnessefixtures/tree/NoSiebel

This contains a few things:
- no siebel, as this needs a closed source jar
- adjusted powercenter dependency and code, to make it fully open source
- added a pom.xml to manage dependencies with that are in maven central
- added ml.options java code as a package in this project with a readme file containing the very limited licence information available from the contributor
- a lot of little edits to reduce the amount of warnings and errors, there is a lot to do here.

As a result, this is now a working maven build of which we can use the jar in our FitNesse installation. Not sure how to proceed from here. Making a PR will remove Siebel support, for example.

The issue I had is now resolved and I put the code in our FitNesse project so we can build it to our needs.

Let me know what you think, looking forward to hear.

**Comment by jacbeekers** [comment]
As you may have found out, the source code for the informatica library is generated as described in https://kb.informatica.com/proddocs/Product%20Documentation/4/PC_961_WebServicesProviderGuide_en.pdf - look for "Java Client Application for Batch Web Services".
I will include the generated source code in the next release. That way, it will be compiled into the ConsagFitNesseFixtures.jar and the informatica_wsh.jar is no longer needed.
With regards to the Siebel jars, it is true that these are not needed for the majority of fixtures and could be part of a separate project. For now, I will leave them in until I've configured gradle correctly.

Having said 'gradle': I've created a build.gradle that builds the code. I will include it in the release 2017.03, that will also contain some minor fixes.

**Comment by jacbeekers** [comment]
The Siebel functionality will be dropped in the 2017.09 release. Siebel supports REST API since 2016, and support for this be will added in a later release. The Java Beans won't be needed anymore.

**Comment by keetron** [comment]
As a suggestion, you can take the REST implementation from HSAC if you want to save yourself a bunch of work:
https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/master/src/main/java/nl/hsac/fitnesse/fixture/slim/JsonHttpTest.java
But no doubt there are more slim fixtures doing something similar.
